# Generated by Django 5.1.6 on 2025-03-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=100)),
                ('CourseTitle', models.CharField(max_length=100)),
                ('Instructor', models.CharField(max_length=100)),
            ],
        ),
    ]
